/**
 * Unlock Copy build.
 *
 * Produces dist/chrome and dist/firefox from one source tree, and optionally
 * zips them for store upload. There is no bundler: shared library files are
 * plain classic scripts that hang off a `UC` global, and this script
 * concatenates them into one background script per target so the Chrome service
 * worker and the Firefox event page run identical, module-free code.
 *
 *   node tools/build.mjs           build both targets
 *   node tools/build.mjs --zip     build, then write store zips
 *   node tools/build.mjs --check   build, then run the release gate
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateRaw } from 'node:zlib';
import { promisify } from 'node:util';

const deflate = promisify(deflateRaw);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

const TARGETS = ['chrome', 'firefox'];

/** Concatenated in order into background.js. Order matters: no forward refs. */
const BACKGROUND_MODULES = [
  'lib/browser.js',
  'lib/policy.js',
  'lib/origins.js',
  'lib/settings.js',
  'lib/registry.js',
  'background.main.js',
];

/** Copied verbatim. `lib` ships too, because the popup and options load it directly. */
const STATIC_DIRS = ['content', 'popup', 'options', 'icons', 'lib'];

/**
 * The entire product promise is that this cannot read your browsing until you
 * point it at a site, so the permission surface is gated by the build rather
 * than by anyone remembering.
 */
const ALLOWED_PERMISSIONS = ['activeTab', 'scripting', 'storage'];
const ALLOWED_OPTIONAL_HOSTS = ['*://*/*'];

/**
 * Chrome Web Store field limits.
 *
 * Both of these are rejected at upload time, not at load time, so a manifest
 * that is perfectly valid locally can still fail on submission. The 132 was
 * learned the hard way: a 145 character description built, loaded and ran fine,
 * then bounced from the store with "It exceeds maximum size limit of 132
 * characters". Cheaper to fail here than after packaging.
 */
const MAX_DESCRIPTION = 132;
const MAX_NAME = 75;
/**
 * `content_scripts` is forbidden on purpose. Declaring one statically would
 * require host permissions at install time, which is exactly the install
 * warning this design exists to avoid; the same scripts are registered at
 * runtime per origin instead.
 */
const FORBIDDEN_MANIFEST_KEYS = ['host_permissions', 'content_scripts', 'externally_connectable'];

const args = new Set(process.argv.slice(2));

async function rmrf(dir) {
  await fs.rm(dir, { recursive: true, force: true });
}

async function copyDir(from, to) {
  await fs.mkdir(to, { recursive: true });
  for (const entry of await fs.readdir(from, { withFileTypes: true })) {
    const s = path.join(from, entry.name);
    const d = path.join(to, entry.name);
    if (entry.isDirectory()) await copyDir(s, d);
    else await fs.copyFile(s, d);
  }
}

/**
 * Chrome and Firefox diverge in exactly two places: how the background script is
 * declared, and Firefox's requirement for an explicit add-on id. Expressing that
 * here beats maintaining two manifests that drift apart.
 */
function manifestFor(target, base) {
  const m = structuredClone(base);
  if (target === 'chrome') {
    m.background = { service_worker: 'background.js' };
    // world: "MAIN" on a registered content script is the floor, and it landed
    // in Chrome 111. Without it the persistent unlock cannot run early, which
    // is the only mode that beats a listener registered on window in capture.
    m.minimum_chrome_version = '111';
  } else {
    // Firefox MV3 uses a non-persistent event page, not a service worker.
    m.background = { scripts: ['background.js'] };
    m.browser_specific_settings = {
      gecko: {
        id: 'unlock-copy@tiltedlunar.dev',
        // Two floors apply and the higher wins:
        //  - 128 is when Firefox gained world: "MAIN".
        //  - 140 is when data_collection_permissions became supported, and AMO
        //    requires that key on new submissions.
        strict_min_version: '140.0',
        data_collection_permissions: { required: ['none'] },
      },
      // Android picked up data_collection_permissions later than desktop.
      gecko_android: { strict_min_version: '142.0' },
    };
  }
  return m;
}

async function buildBackground() {
  const parts = [
    '/* Unlock Copy background bundle. Generated by tools/build.mjs - do not edit. */',
    "'use strict';",
  ];
  for (const rel of BACKGROUND_MODULES) {
    const code = await fs.readFile(path.join(SRC, rel), 'utf8');
    parts.push(`\n/* ---- ${rel} ---- */\n${code}`);
  }
  return parts.join('\n');
}

async function buildTarget(target, base, background) {
  const out = path.join(DIST, target);
  await rmrf(out);
  await fs.mkdir(out, { recursive: true });

  for (const dir of STATIC_DIRS) {
    await copyDir(path.join(SRC, dir), path.join(out, dir));
  }
  await fs.writeFile(path.join(out, 'background.js'), background);
  await fs.writeFile(
    path.join(out, 'manifest.json'),
    JSON.stringify(manifestFor(target, base), null, 2) + '\n'
  );
  return out;
}

/* ------------------------------------------------------------------ */
/* Release gate                                                        */
/* ------------------------------------------------------------------ */

async function check(base) {
  const problems = [];

  for (const target of TARGETS) {
    const dir = path.join(DIST, target);
    const manifest = JSON.parse(await fs.readFile(path.join(dir, 'manifest.json'), 'utf8'));
    const tag = `[${target}]`;

    for (const p of manifest.permissions ?? []) {
      if (!ALLOWED_PERMISSIONS.includes(p)) problems.push(`${tag} unexpected permission "${p}"`);
      if (p.includes('://') || p === '<all_urls>') {
        problems.push(`${tag} host permission "${p}" must never ship in permissions`);
      }
    }

    // Optional hosts are the whole persistence design, but they must stay
    // optional and must stay exactly this one pattern.
    const optional = manifest.optional_host_permissions ?? [];
    for (const p of optional) {
      if (!ALLOWED_OPTIONAL_HOSTS.includes(p)) {
        problems.push(`${tag} unexpected optional host permission "${p}"`);
      }
    }
    if (optional.length === 0) {
      problems.push(`${tag} optional_host_permissions missing; "always unlock" cannot work`);
    }

    for (const key of FORBIDDEN_MANIFEST_KEYS) {
      if (key in manifest) problems.push(`${tag} manifest must not declare "${key}"`);
    }

    if (manifest.version !== base.version) {
      problems.push(`${tag} version drifted from base manifest`);
    }

    if ((manifest.description ?? '').length > MAX_DESCRIPTION) {
      problems.push(
        `${tag} description is ${manifest.description.length} characters, ` +
          `over the store limit of ${MAX_DESCRIPTION}`
      );
    }
    if ((manifest.name ?? '').length > MAX_NAME) {
      problems.push(
        `${tag} name is ${manifest.name.length} characters, over the store limit of ${MAX_NAME}`
      );
    }

    for (const [size, rel] of Object.entries(manifest.icons ?? {})) {
      const file = path.join(dir, rel);
      let buf;
      try {
        buf = await fs.readFile(file);
      } catch {
        problems.push(`${tag} icon ${size} missing: ${rel}`);
        continue;
      }
      const isPng = buf.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]));
      if (!isPng) {
        problems.push(`${tag} icon ${size} is not a PNG: ${rel}`);
        continue;
      }
      // PNG IHDR carries width and height as big-endian uint32 at 16 and 20.
      const w = buf.readUInt32BE(16);
      const h = buf.readUInt32BE(20);
      if (w !== Number(size) || h !== Number(size)) {
        problems.push(`${tag} icon ${size} is ${w}x${h}, expected ${size}x${size}`);
      }
    }

    const pages = [manifest.action?.default_popup, manifest.options_ui?.page].filter(Boolean);
    for (const page of pages) {
      try {
        await fs.access(path.join(dir, page));
      } catch {
        problems.push(`${tag} missing page referenced by manifest: ${page}`);
      }
    }

    // Every file the runtime registration names has to exist, or "always
    // unlock" fails silently at register time on a user's machine.
    for (const rel of ['content/unlock.js', 'content/bridge.js']) {
      try {
        await fs.access(path.join(dir, rel));
      } catch {
        problems.push(`${tag} missing registered content script: ${rel}`);
      }
    }

    const bg = await fs.readFile(path.join(dir, 'background.js'), 'utf8');
    for (const banned of ['importScripts(', 'eval(', 'new Function(']) {
      if (bg.includes(banned)) problems.push(`${tag} background uses forbidden "${banned}"`);
    }
  }

  // Nothing you copy may leave the machine. Gated, not merely promised.
  const netCalls = [];
  await walk(SRC, async (file) => {
    if (!/\.(js|html)$/.test(file)) return;
    const text = await fs.readFile(file, 'utf8');
    const rel = path.relative(ROOT, file);
    // Comments and string literals are blanked first, so prose that mentions an
    // API does not fail a file that never calls it.
    const code = blankCommentsAndStrings(text);
    for (const m of code.matchAll(/\b(fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon)\s*\(/g)) {
      netCalls.push(`${rel}:${code.slice(0, m.index).split('\n').length} ${m[1]}(`);
    }
  });
  for (const call of netCalls) problems.push(`network call in shipped source -> ${call}`);

  // Every shipped script must parse. A syntax error in a content script is
  // invisible until a user hits the site it was supposed to fix.
  for (const target of TARGETS) {
    await walk(path.join(DIST, target), async (file) => {
      if (!file.endsWith('.js')) return;
      const source = await fs.readFile(file, 'utf8');
      // eslint-disable-next-line no-control-regex
      if (/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(source)) {
        problems.push(`[${target}] control characters in ${path.relative(ROOT, file)}`);
      }
    });
  }

  if (problems.length) {
    console.error('\nRelease gate FAILED:\n' + problems.map((p) => `  x ${p}`).join('\n') + '\n');
    process.exit(1);
  }
  console.log(
    'Release gate passed: permissions, optional hosts, store field limits, icons, pages, content scripts, no remote code, no network.'
  );
}

/**
 * Replace comments and string/template literals with spaces, preserving byte
 * offsets and newlines so reported line numbers stay accurate.
 *
 * A scanner rather than a regex, because a regex cannot tell a comment from a
 * `//` inside a URL string, and getting that wrong either hides a real call or
 * blocks a clean build.
 */
function blankCommentsAndStrings(source) {
  const out = source.split('');
  const blank = (from, to) => {
    for (let k = from; k < to && k < out.length; k++) {
      if (out[k] !== '\n') out[k] = ' ';
    }
  };

  let i = 0;
  while (i < source.length) {
    const two = source.slice(i, i + 2);

    if (two === '//') {
      const end = source.indexOf('\n', i);
      const stop = end === -1 ? source.length : end;
      blank(i, stop);
      i = stop;
      continue;
    }
    if (two === '/*') {
      const end = source.indexOf('*/', i + 2);
      const stop = end === -1 ? source.length : end + 2;
      blank(i, stop);
      i = stop;
      continue;
    }

    const ch = source[i];
    if (ch === '"' || ch === "'" || ch === '`') {
      let j = i + 1;
      while (j < source.length) {
        if (source[j] === '\\') {
          j += 2;
          continue;
        }
        if (source[j] === ch) break;
        // An unterminated single quote is almost certainly an apostrophe in
        // prose; stop at the newline rather than eating the rest of the file.
        if (source[j] === '\n' && ch !== '`') break;
        j++;
      }
      blank(i + 1, j);
      i = j + 1;
      continue;
    }
    i++;
  }
  return out.join('');
}

async function walk(dir, fn) {
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) await walk(full, fn);
    else await fn(full);
  }
}

/* ------------------------------------------------------------------ */
/* Zip writer (store upload format, no dependencies)                   */
/* ------------------------------------------------------------------ */

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

/** Minimal deflate zip, so packaging a release needs no dependency. */
async function writeZip(sourceDir, zipPath) {
  const files = [];
  await walk(sourceDir, async (full) => {
    files.push({
      name: path.relative(sourceDir, full).split(path.sep).join('/'),
      data: await fs.readFile(full),
    });
  });
  files.sort((a, b) => a.name.localeCompare(b.name));

  const chunks = [];
  const central = [];
  let offset = 0;

  for (const f of files) {
    const nameBuf = Buffer.from(f.name, 'utf8');
    const crc = crc32(f.data);
    const compressed = await deflate(f.data, { level: 9 });
    const useDeflate = compressed.length < f.data.length;
    const body = useDeflate ? compressed : f.data;
    const method = useDeflate ? 8 : 0;

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0, 6);
    local.writeUInt16LE(method, 8);
    local.writeUInt16LE(0, 10);
    local.writeUInt16LE(0x21, 12); // deterministic date
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(body.length, 18);
    local.writeUInt32LE(f.data.length, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28);
    chunks.push(local, nameBuf, body);

    const cd = Buffer.alloc(46);
    cd.writeUInt32LE(0x02014b50, 0);
    cd.writeUInt16LE(20, 4);
    cd.writeUInt16LE(20, 6);
    cd.writeUInt16LE(0, 8);
    cd.writeUInt16LE(method, 10);
    cd.writeUInt16LE(0, 12);
    cd.writeUInt16LE(0x21, 14);
    cd.writeUInt32LE(crc, 16);
    cd.writeUInt32LE(body.length, 20);
    cd.writeUInt32LE(f.data.length, 24);
    cd.writeUInt16LE(nameBuf.length, 28);
    cd.writeUInt16LE(0, 30);
    cd.writeUInt16LE(0, 32);
    cd.writeUInt16LE(0, 34);
    cd.writeUInt16LE(0, 36);
    cd.writeUInt32LE(0, 38);
    cd.writeUInt32LE(offset, 42);
    central.push(cd, nameBuf);

    offset += local.length + nameBuf.length + body.length;
  }

  const centralBuf = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(files.length, 8);
  end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(centralBuf.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20);

  await fs.writeFile(zipPath, Buffer.concat([...chunks, centralBuf, end]));
  return files.length;
}

/* ------------------------------------------------------------------ */

async function main() {
  const base = JSON.parse(await fs.readFile(path.join(SRC, 'manifest.base.json'), 'utf8'));
  const background = await buildBackground();

  for (const target of TARGETS) {
    const out = await buildTarget(target, base, background);
    console.log(`built ${target} -> ${path.relative(ROOT, out)}`);
  }

  if (args.has('--zip')) {
    await fs.mkdir(path.join(ROOT, 'release'), { recursive: true });
    for (const target of TARGETS) {
      const zip = path.join(ROOT, 'release', `unlock-copy-${target}-v${base.version}.zip`);
      const n = await writeZip(path.join(DIST, target), zip);
      console.log(`zipped ${target} (${n} files) -> ${path.relative(ROOT, zip)}`);
    }
  }

  if (args.has('--check')) await check(base);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
